---
default:
  threads: 6
  producer_type: BaseProducer
  producer_config:
    bootstrap.servers: ""
    security.protocol: "SASL_SSL"
    sasl.mechanism: "SCRAM-SHA-256"
    sasl.username: "admin"
    sasl.password: ""
    # ssl.ca.location: "..ca.crt"
    queue.buffering.max.ms: 100
    queue.buffering.max.messages: 1000000

scenarios:
  10B_bursts:
    repeat_times: 5
    repeat_pause: 10
    topic: benchmark
    message_size: 10
    message_count: 1

  1KB_bursts:
    repeat_times: 3
    repeat_pause: 20
    topic: benchmark_topic_1KB
    message_size: 1024
    message_count: 500000

  10KB_bursts:
    repeat_times: 3
    repeat_pause: 0
    topic: benchmark_topic_10KB
    message_size: 10240
    # message_size: 10
    message_count: 100000
    # message_count: 1
